### ISSUE TITLE
Newer versions of requests library cause HTTP header issue

### ISSUE THREAD

**Issue by ApexMuse** [Azure/azure-documentdb-python#89]
- `CurrentMediaStorageUsageInMB`: int, current attachment content
          (media) usage in MBs (Retrieved from gateway ).

HTTP headers in the latest versions of the request library cause the following error:
requests.exceptions.InvalidHeader: Header value 0 must be of type str or bytes, not <class 'int'>

Judging from a quick lookup in the code, the 'CurrentMediaStorageUsageInMB' value seems to be the culprit.

**Comment by mideeks** [comment]
I am running into this now too. It looks like there was a PR opened that fixed this but was closed because of something with unit tests:
https://github.com/Azure/azure-documentdb-python/pull/84

Can one of the maintainers please look at this and fix? We are unable to use pydocumentdb with the latest version of requests.

**Comment by rnagpal** [comment]
@ApexMuse @mideeks If you install the pydocumentdb package using requirements.txt it should install the working version(2.10.0) of the requests module in your virtual environment and use that instead of the latest version that has issues. Anyways, will we look into to merging this as part of our upcoming release.

**Comment by mideeks** [comment]
Yes but this forces us to use an old version of requests in our entire project.

**Comment by rnagpal** [comment]
@ApexMuse @mideeks The fix for this will be released next week.

**Comment by lediur** [comment]
Is there an update for when the fix might be available?

**Comment by skasturi** [comment]
We are waiting for update on this as well. Can you please let us know if this is fixed? @rnagpal

**Comment by rnagpal** [comment]
The fix is checked in to our internal repo. I'll get the release out in next few days.

**Comment by rnagpal** [comment]
We have fixed this issue in the Python SDK 2.1.0 release. Please let us know if you run into any issues.
